workflows:
  - name: sample_demo_a
    source:
      type: local
      location: examples/sample_demo

    adapter: command

    steps:
      - name: run_demo
        command: python run.py

    execution:
      continue_on_failure: false
      retries: 0
      timeout_seconds: 30
      resume_from_checkpoint: false

  - name: failing_demo
    source:
      type: local
      location: examples/failing_demo

    adapter: command

    steps:
      - name: fail_step
        command: python run.py

    execution:
      continue_on_failure: true
      retries: 0
      timeout_seconds: 30
      resume_from_checkpoint: false
