workflows:
  - name: project_alpha
    source:
      type: local
      location: examples/project_alpha

    adapter: command

    steps:
      - name: execute
        command: python run.py

    execution:
      continue_on_failure: false
      retries: 1
      timeout_seconds: 30
      resume_from_checkpoint: false

  - name: project_beta
    source:
      type: local
      location: examples/project_beta

    adapter: command

    steps:
      - name: execute
        command: python run.py

    execution:
      continue_on_failure: false
      retries: 0
      timeout_seconds: 30
      resume_from_checkpoint: false